### ISSUE TITLE
Can't run `chasm`

### ISSUE THREAD

**Issue by gsuuon** [atisharma/chasm_client#4]
I tried to give this a shot but couldn't get it to run:

```
Traceback (most recent call last):
  File "/home/gsuuon/miniconda3/envs/chasm/bin/chasm", line 5, in <module>
    from chasm.repl import run
ImportError: cannot import name 'run' from 'chasm.repl' (/home/gsuuon/miniconda3/envs/chasm/lib/python3.11/site-packages/chasm/repl.hy)
```

I'm running with a conda env in WSL

**Comment by atisharma** [comment]
Apologies, should be fixed with the last commit. Please reopen if you have further trouble.

Also, please let me know how it looks in windows terminal (I've only tried on linux).
